// Integration under tools/prefs-smoke.sh's private GTK display and memory settings.
import Adw from 'gi://Adw';
import Gio from 'gi://Gio';
import GLib from 'gi://GLib';
import GObject from 'gi://GObject';
import Gtk from 'gi://Gtk';
import System from 'system';
import {addPopupControls, popupPresentationPage} from '../lib/prefs/popup.js';
const root = GLib.path_get_dirname(GLib.path_get_dirname(import.meta.url.replace('file://', '')));
const source = Gio.SettingsSchemaSource.new_from_directory(`${root}/schemas`, null, false);
const live = ARGV.includes('live');
const registryKey = live ? 'connectors' : 'demo-connectors';
const orderKey = live ? 'popup-connector-order' : 'demo-popup-connector-order';
const hiddenKey = live ? 'popup-hidden-connectors' : 'demo-popup-hidden-connectors';
const otherHiddenKey = live ? 'demo-popup-hidden-connectors' : 'popup-hidden-connectors';
const connectorIds = live ? ['codex--00000000-0000-4000-8000-000000000001',
    'claude--00000000-0000-4000-8000-000000000002', 'antigravity--00000000-0000-4000-8000-000000000003'] : ['codex', 'claude', 'antigravity'];
const [codexId, claudeId, antigravityId] = connectorIds;
const app = new Adw.Application({application_id: 'io.github.dandgabr.QuotaPopupTest', flags: Gio.ApplicationFlags.NON_UNIQUE});
const wait = () => new Promise(resolve => GLib.timeout_add(GLib.PRIORITY_DEFAULT, 350, () => { resolve(); return GLib.SOURCE_REMOVE; }));
const check = (value, message) => { if (!value) throw new Error(message); };
function walk(widget) {
    const widgets = [widget];
    for (let child = widget.get_first_child(); child; child = child.get_next_sibling()) widgets.push(...walk(child));
    return widgets;
}
let failed = false;
app.connect('activate', () => {
    app.hold();
    (async () => {
        const settings = Gio.Settings.new_full(source.lookup('org.gnome.shell.extensions.gnome-ai-quota', false), Gio.memory_settings_backend_new(), null);
        const window = new Adw.PreferencesWindow({application: app, default_width: 640, default_height: 600});
        const page = new Adw.PreferencesPage({title: 'General'});
        const group = new Adw.PreferencesGroup({title: 'Popup'});
        const handlerIds = [];
        addPopupControls({group, window, settings, gettext: s => s, handlerIds});
        page.add(group); window.add(page); window.present(); await wait();
        const rows = walk(group);
        const automaticWidth = rows.find(row => row instanceof Adw.SwitchRow && row.title === 'Automatic width');
        const width = rows.find(row => row instanceof Adw.SpinRow && row.title === 'Popup width');
        check(automaticWidth.active && !width.sensitive && settings.get_int('popup-width') === 0, 'Automatic width never writes its displayed fallback');
        automaticWidth.active = false; width.value = 580;
        check(settings.get_int('popup-width') === 580, 'Manual width reaches settings');
        settings.reset('popup-width');
        check(automaticWidth.active && settings.get_int('popup-width') === 0, 'Reset follows settings without writing back');
        settings.set_string('data-source', live ? 'live' : 'demo');
        const entries = ['codex', 'claude'].map((providerId, i) => ({id: connectorIds[i], providerId, label: '', username: ''}));
        const registry = entries => JSON.stringify({version: 1, connectors: entries});
        settings.set_string(registryKey, registry(entries));
        const baseHandlers = handlerIds.length;
        const presentation = popupPresentationPage({window, settings, gettext: s => s, handlerIds});
        window.push_subpage(presentation); await wait();
        check(handlerIds.length === baseHandlers + 7, 'Opening the subpage keeps settings subscriptions active');
        const connectorRows = () => walk(presentation).filter(row => row instanceof Adw.ActionRow && row.subtitle === 'Show in popup');
        const codex = connectorRows().find(row => row.title === 'Codex');
        const switchFor = row => walk(row).find(widget => widget instanceof Gtk.Switch);
        // Update after controls exist; the old Codex handler must preserve the new sibling.
        const third = {id: antigravityId, providerId: 'antigravity', label: '', username: ''};
        settings.set_string(registryKey, registry([...entries, third]));
        check(connectorRows().some(row => row.title === 'Antigravity'), 'Registry additions update the open list');
        settings.set_strv(hiddenKey, [antigravityId]);
        switchFor(codex).active = false;
        check(JSON.stringify(settings.get_strv(hiddenKey)) === JSON.stringify([antigravityId, codexId]), 'Hiding preserves a newly added hidden sibling');
        const claude = connectorRows().find(row => row.title === 'Claude');
        const up = walk(claude).find(widget => widget instanceof Gtk.Button && widget.tooltip_text === 'Move up');
        up.grab_focus();
        up.emit('clicked');
        await wait();
        check(JSON.stringify(settings.get_strv(orderKey)) === JSON.stringify([claudeId, codexId, antigravityId]), 'Clicking Move up persists the reordered IDs');
        check(connectorRows()[0].title === 'Claude', 'Clicking Move up moves the visible row');
        check(window.get_focus()?.is_ancestor(claude) && window.get_focus().sensitive, 'Moving to first row retains focus on an enabled action of the same connector');
        const down = walk(claude).find(widget => widget instanceof Gtk.Button && widget.tooltip_text === 'Move down');
        down.grab_focus(); down.emit('clicked'); await wait();
        check(JSON.stringify(settings.get_strv(orderKey)) === JSON.stringify([codexId, claudeId, antigravityId]), 'Clicking Move down persists the reordered IDs');
        check(JSON.stringify(connectorRows().map(row => row.title)) === JSON.stringify(['Codex', 'Claude', 'Antigravity']), 'Clicking Move down reorders the visible list');
        down.grab_focus(); down.emit('clicked'); await wait();
        check(JSON.stringify(settings.get_strv(orderKey)) === JSON.stringify([codexId, antigravityId, claudeId]), 'Repeated movement uses current order');
        check(JSON.stringify(connectorRows().map(row => row.title)) === JSON.stringify(['Codex', 'Antigravity', 'Claude']), 'Repeated movement updates every visible row');
        check(window.get_focus()?.is_ancestor(claude) && window.get_focus().sensitive, 'Moving to last row retains focus on an enabled action of the same connector');
        check(settings.get_strv('untracked-providers').length === 0 && settings.get_strv(otherHiddenKey).length === 0, 'Presentation remains separate from polling and the other data source');
        window.hide(); await wait(); window.present(); await wait();
        check(handlerIds.length === baseHandlers + 7, 'Temporarily hiding the window retains subscriptions');
        settings.set_strv(orderKey, [claudeId, codexId, antigravityId]);
        check(connectorRows()[0].title === 'Claude', 'Restored window keeps reacting to external order changes');
        const firstOwnedHandlers = handlerIds.slice(baseHandlers);
        window.pop_subpage(); await wait();
        check(handlerIds.length === baseHandlers, 'Leaving presentation disconnects owned settings handlers');
        check(firstOwnedHandlers.every(id => !GObject.signal_handler_is_connected(settings, id)), 'Leaving the subpage actually disconnects its settings signals');
        const reopened = popupPresentationPage({window, settings, gettext: s => s, handlerIds});
        window.push_subpage(reopened); await wait();
        const reopenedRows = () => walk(reopened).filter(row => row instanceof Adw.ActionRow && row.subtitle === 'Show in popup');
        check(reopenedRows()[0].title === 'Claude', 'Reopening uses the saved order');
        const lastRow = reopenedRows()[2];
        const reopenedUp = walk(lastRow).find(widget => widget instanceof Gtk.Button && widget.tooltip_text === 'Move up');
        reopenedUp.emit('clicked'); await wait();
        check(reopenedRows()[1].title === 'Antigravity', 'Reopened arrows remain functional');
        const reopenedOwnedHandlers = handlerIds.slice(baseHandlers);
        window.close(); await wait();
        check(handlerIds.length === baseHandlers, 'Closing the window disconnects subpage settings handlers');
        check(reopenedOwnedHandlers.every(id => !GObject.signal_handler_is_connected(settings, id)), 'Closing the window actually disconnects its settings signals');
        handlerIds.splice(0).forEach(id => settings.disconnect(id));
        print(`GAQ_PREFS_POPUP_OK: ${live ? 'live scoped IDs' : 'demo'}, dimensions, reset, stale-registry visibility, rendered order, isolation and cleanup`);
    })().catch(error => { printerr(error.stack); failed = true; }).finally(() => { app.release(); app.quit(); });
});
app.run([]);
System.exit(failed ? 1 : 0);
